### ISSUE TITLE
How do i use Fp16 when training with my dataset? Cuda out of memory!

### ISSUE THREAD

**Issue by crypticsymmetry** [NVIDIA/pix2pixHD#101]
Trying to use less memory with my dataset. Can i use fp16 for training? Am i missing something? can i use Apex/amp? If so how do i add it? btw i am very new to all of this. 
Ubuntu 18.04 , rtx 2070 , cuda 10 , pytorch nightly. Need anything else?
Thanks!

**Comment by thomasjhuang** [comment]
Per the instructions in the README, you need to install apex, and then use --fp16 for training. Is this what you were asking?

**Comment by crypticsymmetry** [comment]
Sorry yeah. I Should have closed this. Thanks!
