### ISSUE TITLE
What is the best approach to guarantee valid clusters?

### ISSUE THREAD

**Issue by antocapp** [NVIDIA/pix2pixHD#103]
Hello, 

I am trying to generate infrared images starting from labels. Objects in infrared images may have different parts hotter than other (for example in a car, the front part may be hot in an image, while cold in another, as well as wheels, rear part, or the overall vehicle body). 

I have run several training and the results are quiet discrete for my purpose (which is to generate 10 different infrared images from 10 different clusters, preferably images that make sense - so to have parts of the car hotter or colder depending on the cluster) but still not very good. 

What are some approaches that I may improve to ameliorate the clusters?
Thanks

**Comment by daeunni** [comment]
Hi, did you solve this issue?
