### ISSUE TITLE
Orderly 8*8 pixels patches in output image

### ISSUE THREAD

**Issue by cfanyyx** [NVIDIA/pix2pixHD#109]
I found a very interesting thing. No matter how I change the n_downsampling, n_blocks, kernel size of nn.ConvTranspose2d, kernel size of downsampling nn.Conv2d, kernel size of the final nn.Conv2d, loadSize, fineSize, size of output image, there are always 8*8 pixels patches in output image like the one below. Could anybody explain this?
![image](https://user-images.githubusercontent.com/7723243/54665184-3e231000-4b21-11e9-8a9d-a198129f4a6d.png)

**Comment by luser350** [comment]
@cfanyyx have you solved it, I have a small patch problem in every output.
![epoch008_synthesized_image](https://github.com/NVIDIA/pix2pixHD/assets/168648774/39671bb1-a5e4-4086-a28c-0d5d6f20f85d)
