### ISSUE TITLE
I have an error when test  "python train_512_p.py...",  it stoped at just the 12th epoch

### ISSUE THREAD

**Issue by sxudai** [NVIDIA/pix2pixHD#117]
error as following, cuda 8.0,  pytorch 1.0

Traceback (most recent call last):
  File "train.py", line 87, in <module>
    errors = {k: v.data[0] if not isinstance(v, int) else v for k, v in loss_dict.items()}
  File "train.py", line 87, in <dictcomp>
    errors = {k: v.data[0] if not isinstance(v, int) else v for k, v in loss_dict.items()}
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

is that means i need tensorfollow

**Comment by naren142** [comment]
use v.item() instead of v.item[0] in line 87.

**Comment by sxudai** [comment]
> use v.item() instead of v.item[0] in line 87.

i also solve it by using pytorch 0.4.
