### ISSUE TITLE
error trying to train 1024p net on 12G with --no_instance --label_nc 0

### ISSUE THREAD

**Issue by deepsea1001** [NVIDIA/pix2pixHD#16]
first, amazing work! 
I have successfully trained a 512p network using --no_instance --label_nc 0 and it works great. 
I am now trying to train it up to 1024p following your example in train_1024p_12G.sh. I modify the command by again adding --no_instance and --label_nc 0 (which I seem to need to get the tensor sizes to match)  but when I start training I get this error:

---------- Networks initialized -------------
Pretrained network G has fewer layers; The following are not initialized:
Traceback (most recent call last):
  File "~/pix2pixHD/models/base_model.py", line 63, in load_network
    network.load_state_dict(torch.load(save_path))
  File "~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 490, in load_state_dict
    .format(name))
KeyError: 'unexpected key "model.38.weight" in state_dict'

A couple other errors follow on after that ("During handling of the above exception, another exception occurred:"), but the above seems to be the fail point.

Any ideas on how to get this training?

Thanks!

**Comment by hoomanNo5** [comment]
How did you setup the training images? I'm still at a loss as to how they labeled the segmented images for training or test.

**Comment by tcwang0509** [comment]
The global generator should not contain model.38 when training 1024p; What's model.38 in the printed arch? Are you sure you added all the necessary commands as in train_1024p.sh?

**Comment by tcwang0509** [comment]
"During handling of the above exception, another exception occurred...."
So the issue is actually what happens next. If you are using python3, my guess is it's due to the set library.
Please replace line 73-74 in models/base_model.py with "not_initialized = set()", or pull the latest version.

**Comment by deepsea1001** [comment]
Thanks, that works. The model loads and starts training, but quickly throws:
RuntimeError: CUDA error: out of memory

I am training on a TitanV, 12GB. I currently run my display off of it as well so it looks like 11.4 GB is available for training. If I install my old 980ti and run the display off that, any chance this will train?
