### ISSUE TITLE
About Super Resolution with pix2pixHD

### ISSUE THREAD

**Issue by StepOITD** [NVIDIA/pix2pixHD#17]
Hi, I'm trying to do a Super Resolution job with 1024*1024 images.
And I'm supposed to transform some low-resolution images into high-resolution ones, but i do not know how to name my inputs, is there any rules of naming? And which path should I put my low-resolution images and high-resolution images?

**Comment by tcwang0509** [comment]
You mean the naming for folders or naming for images? If you use the latest version, you should put images under folders named 'train_A' and 'train_B', respectively. There's no rule for image names.
