### ISSUE TITLE
when i check my results image

### ISSUE THREAD

**Issue by qkwmvh321** [NVIDIA/pix2pixHD#171]
hi i trained my own datsets and that was really success
when i check my trained image it's looking really good
but when i test my other test data it's really bad it just make a shape a little bit.....
i tested ngf 32 and 64 all, and ngf 64 is really bad and ngf 32 is better than 64 
but it still make a little bit shape
and i trained my own datasets --no_instance --label_nc 0 
what happends???

**Comment by MuhammadAsadJaved** [comment]
> hi i trained my own datsets and that was really success
> when i check my trained image it's looking really good
> but when i test my other test data it's really bad it just make a shape a little bit.....
> i tested ngf 32 and 64 all, and ngf 64 is really bad and ngf 32 is better than 64
> but it still make a little bit shape
> and i trained my own datasets --no_instance --label_nc 0
> what happends???

same with me

**Comment by ne1114** [comment]
Was there a fix?

**Comment by ne1114** [comment]
> hi i trained my own datsets and that was really success
> when i check my trained image it's looking really good
> but when i test my other test data it's really bad it just make a shape a little bit.....
> i tested ngf 32 and 64 all, and ngf 64 is really bad and ngf 32 is better than 64
> but it still make a little bit shape
> and i trained my own datasets --no_instance --label_nc 0
> what happends???

How did you fix it?

**Comment by songyn95** [comment]
How did you fix it? @MuhammadAsadJaved  @ne1114  @qkwmvh321  @aaronp24  @lukeyeager

**Comment by kgradon98** [comment]
same with me, do u have the solution? @MuhammadAsadJaved @ne1114 @qkwmvh321 @songyn95 @aaronp24

**Comment by YangBo0411** [comment]
same with me, How did you fix it?
