### ISSUE TITLE
What could be the solution for automatically Document Image Unwarping caused by 3d warping ? Is that possible by using pix2pixHD ?

### ISSUE THREAD

**Issue by NavpreetDevpuri** [NVIDIA/pix2pixHD#201]
What is the best solution for Document Image Unwarping caused by 3d warping ?<br>
### In my case i just want very simple unwarping as follow 
1. Always having similar backgroud 
2. Always Placing page at similar position
3. Always having same type of wraped image
![ApplicationFrameHost_OBhqMlLofR](https://user-images.githubusercontent.com/30471072/85190964-bf47f480-b2da-11ea-8e76-3a2ee296f854.png)

## I tried following methods but didn't work out.

 - I tried so many scanning apps but no app can unwarp 3d wrap 
for example this one [microsoft office lens](https://www.bralin.com/microsoft-office-lens-how-to-article)<br>
<img src="https://i.stack.imgur.com/v6Wc4.jpg" height="400" />

 - I tried [page_dewarp.py](https://github.com/mzucker/page_dewarp). But it does not work with pages having spaces between texts or having segments of texts and most of times for that kind of images it just revert cure from left to right or vice versa and also unable to detect actual text area for example<br>
![output of page_dewarp.py](https://i.stack.imgur.com/0C8kx.jpg)

 - I found [deep-learning-for-document-dewarping](https://github.com/thomasjhuang/deep-learning-for-document-dewarping) that is trying to solve this problem by using [pix2pixHD](https://github.com/NVIDIA/pix2pixHD) But i am not sure this is gona work and this project don't have trained models and currectly not solving the problem. should i train a model with just following training data `train_A` - warped input images and `train_B` - unwarped output images as mentioned at [pix2pixHD](https://github.com/NVIDIA/pix2pixHD). I can generate training data by make warped and uwarped images using blender 3d. In this way i can generate so many images by using some scanned book's pages by just rendering uwarped image and warped image it like someone taking photos of pages but virtually.

**Comment by NavpreetDevpuri** [comment]
@tcwang0509 
Please can you help me with this.
i want to train a model for just unwarping(moving pixels likewise in photoshop [Liquify](https://www.youtube.com/watch?v=t6bYRvaSFFc)

**Comment by kissge** [comment]
Hi @NavpreetDevpuri , I’ve just randomly arrived at this page while trying to solve similar problems.
Did you find any good solution?
Thanks in advance.

**Comment by zhangxiaojuan66** [comment]
你好，邮件已收到，祝你万事如意，生活愉快！
