### ISSUE TITLE
Runtime error ValueError: Generator must exist!

### ISSUE THREAD

**Issue by NavpreetDevpuri** [NVIDIA/pix2pixHD#202]
Similar to https://github.com/NVIDIA/pix2pixHD/issues/42
I installed pytorch `conda install pytorch torchvision cudatoolkit=10.2 -c pytorch`
I installed python libraries dominate `pip install dominate`
I tried  https://github.com/NVIDIA/pix2pixHD/issues/42#issuecomment-410091071.  But it does not works.
I tried https://github.com/SikkeyHuang/pix2pixHD/commit/fe7185937c518f70ebb1aa0f550d9f6cc58cda5d. But it does not works.

When i tried `python test.py --name label2city_1024p --netG local --ngf 32 --resize_or_crop none`. It shows following error 
```python
./checkpoints\label2city_1024p\latest_net_G.pth not exists yet!
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    model = create_model(opt)
  File "D:\AI\didoc scanner\pix2pixHD-master\models\models.py", line 13, in create_model
    model.initialize(opt)
  File "D:\AI\didoc scanner\pix2pixHD-master\models\pix2pixHD_model.py", line 58, in initialize
    self.load_network(self.netG, 'G', opt.which_epoch, pretrained_path)
  File "D:\AI\didoc scanner\pix2pixHD-master\models\base_model.py", line 58, in load_network
    raise ValueError('Generator must exist!')
ValueError: Generator must exist!
```

Please fix this error and update pix2pixHD code.

**Comment by NavpreetDevpuri** [comment]
My mistake `./checkpoints\label2city_1024p\latest_net_G.pth not exists yet!`
I forgot got to put that file.

**Comment by georgezefko** [comment]
how did you create latest_net_G.pth? i get the same error. I am working on my own dataset

**Comment by NavpreetDevpuri** [comment]
> how did you create latest_net_G.pth? i get the same error on the training part though. I am working on my own dataset
link is given in REAMME
https://drive.google.com/file/d/1h9SykUnuZul7J3Nbms2QGH1wa85nbN2-/view?usp=sharing
