### ISSUE TITLE
Problem training on multiple GPUs

### ISSUE THREAD

**Issue by eyeswideopen** [NVIDIA/pix2pixHD#23]
I'm successfully training the net on my data without specifying GPU ids.
But as soon as i do so i encounter this error:

`Traceback (most recent call last):
  File "train.py", line 56, in <module>
    Variable(data['image']), Variable(data['feat']), infer=save_fake)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 68, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 78, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 67, in parallel_apply
    raise output
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 42, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 4 required positional arguments: 'label', 'inst', 'image', and 'feat'`

The whole code is running inside a docker environment which can access all available GPUs

`>>> torch.cuda.device_count()
8`

my run command looks like this:

`python train.py --name liver_TEST --gpu_ids 0,1,2,3,4,5,6,7 --label_nc 3 --netG local --ngf 32 --num_D 3 --niter_fix_global 20 --fineSize 1024 --no_instance --dataroot ./datasets/liver/
`

Any tips what could be the issue here?
Thanks in advance and this is really awesome work!!

**Comment by eyeswideopen** [comment]
Solution is to not use the default batchsize 1 but to match the available GPUs.
e.g.

`--gpu_ids 0,1,2,3,4,5,6,7 --batchSize 8`

**Comment by npel21** [comment]
@eyeswideopen I am running into this issue currently. My run command is

`python train.py --name test --netG local --ngf 32 --resize_or_crop none --no_instance --loadSize 256 --fineSize 256 --num_D 3 --niter_fix_global 20 --label_nc 0 --no_instance --gpu_ids 0,1 --batchSize 2 --dataroot ./datasets/house
`

I crash about 1000 steps into the first epoch every time. I'm trying to profile the training speed of 256x256 images vs the HD counterparts. My batch size of 2 should match correctly with using the 0,1 for the gpu_ids argument right? Do you think the error is related to using the 256x256 images?

**Comment by eyeswideopen** [comment]
When it crashes at the end of an epoch it is most of the time a mismatch of remaining images and the batchsize.

So in essence your number of training images % batchsize should be 0. 
(just delete training images so it fits...)

**Comment by sevmardi** [comment]
@eyeswideopen  May I ask what kind of GPUs did you use? As soon as I run train.py using ``` --gpu_ids 0,1,2,4,5,6,7 --batchSize 8``` it gets stuck at ```create web directory ./checkpoints/label2city_512p/web..``` Any thoughts?

**Comment by eyeswideopen** [comment]
The system i used to train the model had 8 NVIDIA Tesla P100 with 16Gb of video ram each.

No error message, just stuck indefinitely?

**Comment by sevmardi** [comment]
Yes stuck indefinitely. No errors whatsoever. At some point I kept it running for 2 days straight. Any thoughts how to debug this?

**Comment by eyeswideopen** [comment]
If it is stuck while creating the directory for the web files you could try skipping this step with the option 
`--no_html`
(never tried the option, just found it in options/train_options.py line 13)

**Comment by sevmardi** [comment]
Thanks! Will give it a try now.

**Comment by sevmardi** [comment]
Unfortunately didn't work :( 
still behaving the same way..

**Comment by eyeswideopen** [comment]
I only have wild guesses at the moment but try
`--verbose`
maybe it gives you a little more indication, where it gets stuck. 
If that doesn't help i'd try adding some console prints to identify the code block which causes the error hand try to fix it by hand.
