### ISSUE TITLE
how does the program match the input photo with its corresponding real_image

### ISSUE THREAD

**Issue by 1999kevin** [NVIDIA/pix2pixHD#252]
I have gotten a dataset which contains pairs of photos, labels and ground truth. Is it really enough to place the labels in one directory called train_A and the ground_truth in another directory called train_B? I did my experiment with setting like this but found that the program would find false real_images for some input label? An example is shown below:

![Snip20210319_1](https://user-images.githubusercontent.com/37931674/111746024-69839580-88c8-11eb-8244-c794ff31f389.png)

As what I know in pix2pix, the program takes in pairs of photos, and one pair of photo should be placed in one file.
![Snip20210319_2](https://user-images.githubusercontent.com/37931674/111746292-cc752c80-88c8-11eb-9182-0e586756b674.png)

**Comment by thinklikeanarchitect** [comment]
Pix2pix is different from pix2pixhd from this perspective. You need to create separate folders for Pix2Pix under the dataset folder.

**Comment by 1999kevin** [comment]
> Pix2pix is different from pix2pixhd from this perspective. You need to create separate folders for Pix2PixHD under the dataset folder.

Yes, I have created two folders under the dataset folder. train_A for labels and train_B for real image. But I cannot find the way to link the labels with their corresponding real image. This setting is quite similar with cycleGAN, which indeed does not require pairs of data.

**Comment by thinklikeanarchitect** [comment]
train_A is source image and train_B is target image. Pix2PixHD will generate a fake image. What do you mean by real image? There is no real image in Pix2Pix, as far as I know, real and fake is valid for dcGAN.

**Comment by 1999kevin** [comment]
Sorry for my late reply. For real image, I mean target image. If the photos are placed in two directory, how can the program know the corresponding target photo for each source image? 

> train_A is source (input) image and train_B is target (expected output) image. Pix2PixHD will generate a fake (synthesized) image. What do you mean by real image? There is no real image in Pix2Pix, as far as I know, real and fake is valid for dcGAN.
> 
> 
> 
> Real may be used instead of the target image, I am not sure.

**Comment by thinklikeanarchitect** [comment]
Because you need to name all the images correspondingly. For instance, if the source image in the train_A folder named "sourceX.png", then the target image in the train_B folder should have the exact same name. This is not required for CycleGAN however the way that Pix2Pix matches the source and the target is this.

**Comment by 1999kevin** [comment]
> Because you need to name all the images correspondingly. For instance, if the source image in the train_A folder named "sourceX.png", then the target image in the train_B folder should have the exact same name. This is not required for CycleGAN however the way that Pix2Pix matches the source and the target is this.
> 
> If you have a paired set of images, you need to slice them (image-slicer or any other tool solve this) and the resolution should be 1024x1024 px at least, otherwise crop or resize will be required.

This is what exactly I'm asking for!. Thank you very very much! And I have already gotten sets of images with 1024*1024 resolution.
