### ISSUE TITLE
Issues about size of model

### ISSUE THREAD

**Issue by 1999kevin** [NVIDIA/pix2pixHD#258]
I use the following command to train my model: python train.py --name myname --dataroot ./myroot/ --netG local --label_nc 0 --input_nc 5. It works for me and I can get a good model. However, it seems that the size of model is so large. It is 2.9GB. Is this case normal or I have done something wrong?

**Comment by 1999kevin** [comment]
My dataset contains photo with 1024*1024 pixels

**Comment by kex243** [comment]
Its okay, for example  756 to 512 to10 global blocks is 700mb, 512 to 512 to 13 global blocks is 1gb. If you want to decrease size for some reason (it will affect quality) you can decrease -n_blocks_global. Other parameters are not so heavy weighted.

**Comment by 1999kevin** [comment]
> Its okay, for example 756 to 512 to10 global blocks is 700mb, 512 to 512 to 13 global blocks is 1gb. If you want to decrease size for some reason (it will affect quality) you can decrease -n_blocks_global. Other parameters are not so heavy weighted.

Got it. Thanks very much!

**Comment by alelordelo** [comment]
hi @1999kevin and @kex243, I didn't find the option  _-n_blocks_global_ on the train or base options. How can I use this function? What does it do?

Appreciate any inputs!

**Comment by 1999kevin** [comment]
@alelordelo hi, you can find this option at line 48 in base_options.py.
![image](https://user-images.githubusercontent.com/37931674/116946527-efa74000-acac-11eb-876f-b16b6ea35841.png)

**Comment by alelordelo** [comment]
Thanks a lot for helping! : )

Do you know what this does in terms of quality loss?

**Comment by 1999kevin** [comment]
no sure about it
