### ISSUE TITLE
multi-GPU issues around --no_vgg_loss

### ISSUE THREAD

**Issue by elfprince13** [NVIDIA/pix2pixHD#28]
This code:
https://github.com/NVIDIA/pix2pixHD/blob/db4a24df4a8482089bcb88d0e79c9b484307fc75/models/pix2pixHD_model.py#L160-L172

Causes trouble when using `--no_vgg_loss` with multiple GPUs (and I suspect would also cause trouble for `--no_ganFeat_loss`), because the value `0` is not compatible with the scatter/gather APIs used by `torch.nn.DataParallel`. I suspect it needs to be `Variable` containing a 0-dimensional tensor, but I haven't quite figured out how to make it work.

**Comment by zimbobwe** [comment]
I think may loss_G_VGG = torch.zeros(1).cuda() will figure it out.
