### ISSUE TITLE
Global generator training works well, but local generator does not, why?

### ISSUE THREAD

**Issue by zeyu-hello** [NVIDIA/pix2pixHD#294]
I trained global generator with default config and get good results:
![image](https://user-images.githubusercontent.com/29373801/155926651-4fa96512-f3f9-43c6-9624-c622e483c891.png)
But local generator failed with default config:
![image](https://user-images.githubusercontent.com/29373801/155921469-2528c30e-f30c-4cb7-830e-b13bdd367fed.png)

**Comment by watershadow1212** [comment]
my bro，
How do you do local training? Do you train globally first and then locally?
My training instructions are:
python train.py --name label2LWIR_214_mini_global_then_local --label_nc 3  --gpu_ids 0 --resize_or_crop none --dataroot D:\shuangguangxiagnmuyiqi_Dataset\tule  --continue_train --lr 0.000010
I used annotated images for training, not real images，Unfortunately, my local training was also poor

**Comment by watershadow1212** [comment]
> my bro，
> How do you do local training? Do you train globally first and then locally?
> My training instructions are:
> python train.py --name label2LWIR_214_mini_global_then_local --label_nc 3 --gpu_ids 0 --resize_or_crop none --dataroot D:\shuangguangxiagnmuyiqi_Dataset\tule --continue_train --lr 0.000010
> I used annotated images for training, not real images，Unfortunately, my local training was also poor

my bro，
How do you do local training? Do you train globally first and then locally?
My training instructions are:
python train.py --name label2LWIR_214_mini_global_then_local --label_nc 3 --gpu_ids 0 --resize_or_crop none --dataroot D:\shuangguangxiagnmuyiqi_Dataset\tule --continue_train --lr 0.000010
I used annotated images for training, not real images，Unfortunately, my local training was also poor

**Comment by watershadow1212** [comment]
> I trained global generator with default config and get good results: ![image](https://user-images.githubusercontent.com/29373801/155926651-4fa96512-f3f9-43c6-9624-c622e483c891.png) But local generator failed with default config: ![image](https://user-images.githubusercontent.com/29373801/155921469-2528c30e-f30c-4cb7-830e-b13bdd367fed.png)

my bro，
How do you do local training? Do you train globally first and then locally?
My training instructions are:
python train.py --name label2LWIR_214_mini_global_then_local --label_nc 3 --gpu_ids 0 --resize_or_crop none --dataroot D:\shuangguangxiagnmuyiqi_Dataset\tule --continue_train --lr 0.000010
I used annotated images for training, not real images，Unfortunately, my local training was also poor
