### ISSUE TITLE
TensorRT problem

### ISSUE THREAD

**Issue by ouyangkid** [NVIDIA/pix2pixHD#40]
Installed the tensorrt(3.0 for cuda9.0 and cudnn7.0.5) followed the introduction from the official doc, add the path to ~/.bashrc.
both the python and conda python can import tenosrrt correctly.
However, when I try the example 'python test.py --name label2city_1024p --netG local --ngf 32 --resize_or_crop none '

ERROR: failed to import module (cannot import name onnxparser)
Please make sure you have the TensorRT Library installed
and accessible in your LD_LIBRARY_PATH

How should I add the path to in conda?
Or any other soluations?

**Comment by kenin815** [comment]
You need to upgrade your tensorrt to 4.0 , because only tensorrt 4.0 support onnxparser.

**Comment by ouyangkid** [comment]
@kenin815 Thank you, I upgraded the tensorrt to 4, it works.
however, I  encountered another problem #19, I am studying the parse setting.

**Comment by mykeehu** [comment]
I haven same problem, TensorRT-8.4.3.1.Windows10.x86_64.cuda-11.6.cudnn8.4 installed with graphsurgeon, uff and onnx_graphsurgeon modules.
Any solution?
