### ISSUE TITLE
Cuda out of memory even when trainning 512_p images?

### ISSUE THREAD

**Issue by 594cp** [NVIDIA/pix2pixHD#45]
Hi,I try to train 512_p images using my data.But when I try to run "python train.py --name label2city_512" command,it show cuda out of memory,my set :GPU is 12G,cuda 8.0,pytorch 0.3.I wonder is there anyone have this problem when using examples given in github to train?

**Comment by l2009312042** [comment]
train on 512p takes only 8G memory ，8558MiB / 32480MiB
