### ISSUE TITLE
No module named 'tensorrt'

### ISSUE THREAD

**Issue by fabio-C** [NVIDIA/pix2pixHD#50]
I got an error running the new version of the **test.py** file. In order to do the testing I had to replace this file with an old one (May commit).

```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    from run_engine import run_trt_engine, run_onnx
  File "/home/ubuntu/pix2pixHD/run_engine.py", line 5, in <module>
    import tensorrt
ModuleNotFoundError: No module named 'tensorrt'
```

How can I resolve this?

System Overview: 
Amazon EC2 gpu instance
Deep Learning AMI 10.0 (Ubuntu)
PyTorch with Python3 (CUDA 9.0 and Intel MKL)
Ubuntu 16.04.4 LTS

**Comment by aviel08** [comment]
I had that same error and I tried to reinstall tensorrt over and over again with no luck. 
I just pulled the latest code et voilà! it's working!!!
Thanks!
