### ISSUE TITLE
RuntimeError: invalid argument 0

### ISSUE THREAD

**Issue by fishman2008** [NVIDIA/pix2pixHD#52]
Could you help check the following error? Thanks. The images have the same width and height. But this error appears to related with dimension W? 

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 1184 and 1181 in dimension 2 at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:111

**Comment by tcwang0509** [comment]
What's the image resolution? Make sure the height and width are divisible by 32.

**Comment by fishman2008** [comment]
I have converted it to 128*128 for the experiment test. And the following error occurs again, but with different numbers now. That is sort of weird. 

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 288 and 286 in dimension 2 at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:111

**Comment by tcwang0509** [comment]
Hmm what's the command you're running? It looks like some of your images has dimension 286, and after the network it got rounded to 288, hence the mismatch.

**Comment by fishman2008** [comment]
@tcwang0509 I use the following command:
python train.py --dataroot ./datasets/some-dataset --name pix2pixHD --label_nc 0 --no_instance  --norm batch --no_lsgan --pool_size 0 --resize_or_crop scale_width_and_crop --loadSize 288 --fineSize 256

But new error persists, not sure what is the reason. Do you have a correct command line to perform transformation from RGB-A to RGB-B, pertaining to a specific image size? Thanks.

**Comment by YangBo0411** [comment]
> After changing the parameters to 288, the problem has been solved.

I met the same problem, how did you modify it?

**Comment by zhangxiaojuan66** [comment]
你好，邮件已收到，祝你万事如意，生活愉快！
