### ISSUE TITLE
How do you evaluate the model on the Cityscapes dataset?

### ISSUE THREAD

**Issue by hawjnsafdjlk** [NVIDIA/pix2pixHD#57]
Thanks，that is a great work. How do you evaluate the model on the Cityscapes dataset?
Evaluation metrics include pixel accuracy and mean IOU. Can you share the code?

**Comment by tcwang0509** [comment]
We use the evaluation code from the segmentation network (in our case, PSPNet (https://github.com/hszhao/PSPNet))

**Comment by Erdianna** [comment]
If we train with own dataset where we don't have segments (i.e. we don't have label maps), is there a way to get pixel accuracy?
