### ISSUE TITLE
out of memory when i use own dataset

### ISSUE THREAD

**Issue by guopzhao** [NVIDIA/pix2pixHD#7]
I use the Titan X with 12G memory.
But when i train the model on my own dataset it take the message:
 RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58

my dataset only have RGB image and corresponding labels, I have add the --no_instance, and the classes of label is 23, so I add --label_nc 23

**Comment by mingyuliutw** [comment]
@guopzhao What's the image resolution? For generating 2K images with a single GPU using the preset parameters, you might need to have a GPU card with 24GB memory (e.g., NVIDIA Quadro M6000 GPU). Otherwise, you might need to reduce the number of filters in each convolutional layer.

**Comment by guopzhao** [comment]
@mingyuliutw Thank you for your replay. I use the script  to generate 512p image, the size of  origin image is 400*800, number of class in label is 23,  and the file size is about 500KB. Because I have not the instance map, so I add the --no_instance. Most puzzled me is that the image i used is smaller, but take more GPU memory.
I still have a NVIDIA K80, but is it does not work either. The K80 seems to be two separate units, each with 12G memory.

**Comment by jakeelwes** [comment]
Heya I'm also trying to use my own dataset - worried I may be out of memory when I start training as I only have 8G, but may see if I can run it on 512 & reduce filters. 
I was just wondering how you formatted the data directories? I have an A folder and a B folder but I'm getting `AssertionError: /train_label is not a valid directory` (I dont actually have any labels just corresponding RGB images so I'm using `--label_nc 0`)

**Comment by tcwang0509** [comment]
@guopzhao did you resize the image or keep the original size? Note that the default setting will scale the image. However even so you shouldn't run out of memory. Did it happen at the beginning or after a few iterations?

**Comment by tcwang0509** [comment]
@jakeelwes sorry that's something I forgot to change; even if you dataset don't have any labels, I still search for "train_label" and "train_img" instead of A and B. I will modify it in the next version.

**Comment by icbcbicc** [comment]
It will be better if the 512p model only uses 11G memory since many labs are using 1080Ti which only has 11G memory.
