### ISSUE TITLE
Multi GPUs

### ISSUE THREAD

**Issue by BongBong87** [NVIDIA/pix2pixHD#73]
Hello,
I ran this command for my datasets (only 8 pairs of images) on  server by using Jupyter interface:
python train.py --name DTS --label_nc 0 --no_instance --gpu_ids 0,1,2,3 --batchSize 4

In first epoch, It ran to here:
  ############## Forward Pass ######################
losses, generated = model(Variable(data['label']), Variable(data['inst']),
                                      Variable(data['image']), Variable(data['feat']), infer=save_fake)
and similar to infinite loop. No error was occurred but the program can not continue. I check the status of 4 TitanXp cards. All of them is 100% usage.
Some infor:
4 Nvidia TitanXp
Cuda 9.2 cuaDnn 7.1
Ubuntu core 16.04

p/s: I ran this model in each single GPU, it worked well.
python train.py --name DTS --label_nc 0 --no_instance --gpu_ids 0 --batchSize 4 => worked well
python train.py --name DTS --label_nc 0 --no_instance --gpu_ids 1 --batchSize 4 => worked well
python train.py --name DTS --label_nc 0 --no_instance --gpu_ids 2 --batchSize 4 => worked well
python train.py --name DTS --label_nc 0 --no_instance --gpu_ids 3 --batchSize 4 => worked well
Is there any idea for me? Thanks so much for your help.

**Comment by PhuongChu87** [comment]
For supplement: I used Python 3.5 and Pytorch 0.4.1. Thanks

**Comment by PhuongChu87** [comment]
I don't met your issue. In my case, because of security among multi GPUs. I turned it off and that 's ok

**Comment by ElegantLin** [comment]
Can this code test with multiple GPUs?

I have a 2080 and I used test_1024p.sh. I met a memory out error. I know that the reason is that my memory is not enough. But can I test with more GPUs?

I have tried export command but it failed.

**Comment by tripzero** [comment]
> > I solved it. Thanks
> 
> Hello, I have met the same problem just you said.
> The code worked well in single GPU but failed in multi GPUS.
> And I got an error report ：
> TypeError: forward() missing 4 required positional arguments: 'label', 'inst', 'image', and 'feat'
> 
> Would you please let me know how did you solve the problem?Thx

I saw this error as well.  Using --batchSize 2 seemed to help.
