### ISSUE TITLE
Custom data set training 

### ISSUE THREAD

**Issue by Avyukth** [NVIDIA/pix2pixHD#74]
Can I train any custom RGB Image which don't have any feature map and don't have any label ?
what are the commands ?

**Comment by kleinyoni** [comment]
According to what i see in the init params if you use --no_instance in the train.py commands you wont use the instance map as an input.

Also if you remove "--load_features" from the training commands than you wont load the feature map also.

The last one i tried and it worked(not as good as with the features). The first one i didn't use. I think that then the code will be most similar to what they did in pix2pix.

**Comment by guotong1988** [comment]
Same question. Thank you.
