### ISSUE TITLE
stuck before starting training 

### ISSUE THREAD

**Issue by sevmardi** [NVIDIA/pix2pixHD#75]
right after running the following
```
python train.py --name label2city_512p --gpu_ids 0,1,2,4,5,6,7 --batchSize 8
```
It gets stuck at 
```
create web directory ./checkpoints/label2city_512p/web..

```

Using 
torch 0.4.1 
torchvision 0.2.1  
python 3.6

Someone else having this problem?

**Comment by sevmardi** [comment]
I wish I could!! There is literately nothing happening (at least not from the point I could see something). At one point i let it run for 2 days, it just didn't move a inch forward.

**Comment by sevmardi** [comment]
..And no there is no error.

**Comment by Avyukth** [comment]
are you using any GPU ? it must be 8 GPU you are running , `--batchSize` must be same as no of GPU you are training on .

**Comment by MaxLFarrell** [comment]
I'm having this same problem, I'm trying to diagnose what's going on myself
For background I'm running on Ubuntu 18.04.1 LTS with CUDA 9 and 2 NVIDIA GTX 1060s and my script is as follows:
```
python3 train.py --name oil_2 --dataroot ./datasets/oil_2/ --batchSize 2 --gpu_ids 0,1 --label_nc 0 --no_instance --resize_or_crop scale_width_and_crop
```

**Comment by sevmardi** [comment]
I think I've got something here. I believe this got to do with either Pytorch or GPUs begin used. On the first place I trued on Tesla K80 gpus and got stuck. Now I just had an opportunity to run my experiments on GeForce GTX 980 Ti and seem to work properly. No changes in code or whatsoever.

**Comment by nisargshah1999** [comment]
Hi,

I faced the same issue, it occured for specific pytorch versions, it could be solved by changing pytorch version, it worked for me.
