### ISSUE TITLE
How to generate test_inst?

### ISSUE THREAD

**Issue by MSiam** [NVIDIA/pix2pixHD#77]
In your inference test data you are using test_inst which has the instance Ids. How to generate that on custom images?

**Comment by tcwang0509** [comment]
Well, you can try to use Mask RCNN, or just train without inst information.

**Comment by guotong1988** [comment]
Same question, Thank you.

**Comment by l2009312042** [comment]
the test_instance  have few labels than  test_labels ，such as  just has  cars ，but labels has street tree and  other things .  the instance's   effect is to classify different cars ？so there is only car label？

**Comment by Rubiel1** [comment]
Just to confirm @tcwang0509, I can train with instance maps, and test without instance maps? Thanks.
