### ISSUE TITLE
Can't understand how the lower-resolution network G1 is trained

### ISSUE THREAD

**Issue by andrearama** [NVIDIA/pix2pixHD#81]
I have a doubt coming from reading the paper that is amplified looking at the code:

How is the generator network G1 (the one that produces lower-resolution images) trained? Using the discriminators D1, D2, D3, which are later also used to train the G2 (i.e. the enhancer generator network) ? 

I cannot find these two (or three) distinguished phases in the code, which thus makes me think I am misunderstanding the paper

Thanks

**Comment by tcwang0509** [comment]
The two phases are in two different scripts (train_512p.sh and train_1024p.sh). After you train on lower resolution images using G1, you can continue training another network (G2) on higher resolution images.
