### ISSUE TITLE
Adding or removing objects from the scene

### ISSUE THREAD

**Issue by sevmardi** [NVIDIA/pix2pixHD#82]
In the introduction video you show us how we can add new or remove objects into the environment using for e.g cityscapes dataset. Is this only possible using the UI editor? I understand that you can't share the editor, could you perhaps share notes/guidelines on how to make one ourselves? Would be great!

**Comment by tcwang0509** [comment]
Well, I simply changed the semantic label map to add objects. For example, you can paste a car shape label onto anywhere in the semantic map, and the network will generate a new image with the car synthesized. Removing is similar, you just paste the background.

**Comment by sevmardi** [comment]
@tcwang0509 would it be possible to add new objects into the scene using the command line tools in the package?
